base_url = "https://cyb3rk0tik.github.io"
compile_sass = true

build_search_index = false


[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

[extra]
# Put all your custom variables here
